### ISSUE TITLE
Update for Minecraft 1.9 ?

### ISSUE THREAD

**Issue by unixfox** [Plastix/Plast-Pack#54]
The texture pack doesn't work well with 1.9, can you update it ?

**Comment by Brottweiler** [comment]
It will get updated when it's done. In the 1.9 client it clearly sais that it's uncompatible, so ofcourse it will not work well.

**Comment by Plastix** [comment]
I haven't decided if I am going to keep maintaining this project. Is there something that is completely broken in 1.9?

**Comment by Brottweiler** [comment]
### Broken things
- GUIs (Containers mostly) (slots are in wrong places), also add missing potion effect icons
- Icons and need updating (missing icons)
- Particles need updating (missing particles)

### Other things
- Command block has 4 different textures now, one for each side
  - Repeating command block does not match regular command block
- Frosted ice do not match regular ice
- New boat textures don't match old boat one
- Compass is several files now instead of one stitched file

I think that's all the necessary changes...

**Comment by Brottweiler** [comment]
I've submitted a 1.9 compability update here https://github.com/Plastix/Plast-Pack/pull/55, please take a look at it.

**Comment by Brottweiler** [comment]
2c5715b435c98cb426949be9acec3068328152b5
