### ISSUE TITLE
Dead link in Readme: "oc.tc"

### ISSUE THREAD

**Issue by srwaggon** [Plastix/Plast-Pack#65]
In the readme, there is a dead link in the text "oc.tc" from the following section:

"A PVP customized version of the default Minecraft resource pack. Made for oc.tc! Vivid colors and smooth textures!"

**Comment by Brottweiler** [comment]
Since I archived any other oc.tc link, I could use an archived version of this as well. This [capture](https://web.archive.org/web/20160526185418/https://oc.tc/) is the last one _before_ the shutdown announcement was made, so it makes it the most iconic version of the website. No shutdown, no lifeboat.

**Comment by Brottweiler** [comment]
Another solution would be to change it from a link to `oc.tc`, or just change it to "Overcast Network".

**Comment by Brottweiler** [comment]
Fixed in https://github.com/Plastix/Plast-Pack/commit/b41a2f73952fa447c16443e766ee18c4d71269ba.
